

# Part of Assignment 2 - COMP90024 Cluster and Cloud Computing 2022 S1
#
# Team 28
# 
# Authors: 
#
#  * Yuanzhi Shang (Student ID: 1300135)
#  * Zuguang Tong (Student ID: 1273868)
#  * Ruoyi Gan (Student ID: 987838)
#  * Zixuan Guo (Student ID: 1298930)
#  * Jingyu Tan (Student ID: 1184788)
#
# Location: Melbourne
#

# Clone harvester branch repo
- name: Git clone backend
  git:
    repo: "https://github.com/Joettan/ccc_backend.git"
    dest: "/home/ubuntu/ccc_backend"
  become: yes


# Clear running backend container
- name: Clear backend container
  docker_container:
    name: backend
    state: absent
  become: yes
 
# Clear exsiting backend image
- name: Remove image
  docker_image:
    state: absent
    name: grp28/backend
  become: yes

# Create backend docker image 
- name: Create backend docker image 
  docker_image:
    build:
      path: "/home/ubuntu/ccc_backend/"
      pull: yes
    name: grp28/backend
    source: build
  become: yes

# Run backend
- name: Run backend
  docker_container:
    name: backend
    image: grp28/backend
    state: started
    restart: true
    recreate: true
    restart_policy: on-failure
    restart_retries: 5
    ports:
      - "8080:8080"
  become: yes

# - name: Run backend by shell command
#   ansible.builtin.shell:
#     cmd: docker run -d --name harvester_shell --restart=on-failure:5 grp28/backend
#     chdir: /home/ubuntu/project/tweet_harvesting/
#   become: yes
