version: "3.7"
services:
  frontend:
    container_name: "ccc-frontend"
    build:
      context: ./
      dockerfile: prod.Dockerfile
    env_file:
      - ./.env.production
    ports:
      - "3000:3000"

