# Part of Assignment 2 - COMP90024 Cluster and Cloud Computing 2022 S1
#
# Team 28
# 
# Authors: 
#
#  * Yuanzhi Shang (Student ID: 1300135)
#  * Zuguang Tong (Student ID: 1273868)
#  * Ruoyi Gan (Student ID: 987838)
#  * Zixuan Guo (Student ID: 1298930)
#  * Jingyu Tan (Student ID: 1184788)
#
# Location: Melbourne
#

version: "3.7"
services:
  frontend:
    container_name: "ccc-frontend"
    build:
      context: ./
      dockerfile: prod.Dockerfile
    env_file:
      - ./.env.production
    ports:
      - "3000:3000"

