



# Delete project directory
- name: Delete content & directory
  file:
    state: absent
    path: "/home/ubuntu/project_frontend"
  become: yes

# Clone front end branch
- name: Git clone from remote public repo
  git:
    repo: "https://github.com/ZgTong/Melbourne-s-urban-livability.git"
    dest: "/home/ubuntu/project_frontend"
    version: "data/zuguangt"
  become: true

# # Turn off existing frontend process
# - name: Tear down existing services
#   docker_compose: "/home/ubuntu/project_frontend"
#     project_src: flask
#     state: absent


# # Activate frontend
# - name: Activate frontend
#   docker_compose:
#     project_src: "/home/ubuntu/project_frontend"
#     state: present
#     build: yes
#     pull: yes
#     recreate: always

#   become: yes  