

# Check if project directory exist
- name: Check if the project directory exist
  stat:
    path: /home/ubuntu/Melbourne-s-urban-livability/frontend
  register: stat_result

  
# Clone harvester branch repo
- name: Git clone from remote public repo
  git:
    repo: "https://github.com/ZgTong/Melbourne-s-urban-livability.git"
    dest: "/home/ubuntu/Melbourne-s-urban-livability"
  become: yes


# Turn off existing frontend process
- name: Tear down existing services
  docker_compose: 
    project_src: /home/ubuntu/Melbourne-s-urban-livability/frontend
    state: absent
  become: yes

# Activate frontend
- name: Activate frontend
  docker_compose:
    project_src: /home/ubuntu/Melbourne-s-urban-livability/frontend
    state: present
    build: yes
    pull: yes
    recreate: always
  become: yes  
  register: result

- ansible.builtin.debug:
    var: result


