

# Create and start the couchdb docker container and make them cluster
- hosts: CouchdbAllNodes
  vars_files:
    - host_vars/couchdb_configs.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/id_rsa_ccc.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    - ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: couchdb-startxx

- hosts: CouchdbAllNodes:!CouchdbMaster
  vars_files:
    - host_vars/couchdb_configs.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/id_rsa_ccc.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    - ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: couchdb-make-clusterxx


