



# Deploy common stuff per instances
- hosts: CouchdbAllNodes:&accessNode
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/id_rsa_ccc.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    - ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: instances-common
    - role: instances-volume
    - role: instances-docker
    - role: instances-repo
