

- hosts: localhost
  vars_files:
    - host_vars/mrc_resources.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/id_rsa_ccc.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    - ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: openstack-commonxx
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance


