# Part of Assignment 2 - COMP90024 Cluster and Cloud Computing 2022 S1
#
# Team 28
# 
# Authors: 
#
#  * Yuanzhi Shang (Student ID: 1300135)
#  * Zuguang Tong (Student ID: 1273868)
#  * Ruoyi Gan (Student ID: 987838)
#  * Zixuan Guo (Student ID: 1298930)
#  * Jingyu Tan (Student ID: 1184788)
#
# Location: Melbourne
#

---

- name: Enable Cluster Mode
  uri:
    url: http://{{user}}:{{pass}}@{{masternode}}:5984/_cluster_setup
    method: POST
    force_basic_auth: yes
    status_code: 200, 201
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{\"action\": \"enable_cluster\", \"bind_address\": \"0.0.0.0\", \"username\":\"{{ user }}\", \"password\": \"{{ pass }}\", \"port\": \"5984\", \"remote_node\": \"{{ inventory_hostname }}\", \"node_count\": \"3\",\"remote_current_user\": \"{{ user }}\", \"remote_current_password\":\"{{ pass }}\"}"

- name: Join Cluster
  uri:
    url: http://{{user}}:{{pass}}@{{masternode}}:5984/_cluster_setup
    method: POST
    force_basic_auth: yes
    status_code: 200, 201
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{\"action\":\"add_node\",\"host\":\"{{ inventory_hostname }}\",\"port\":\"5984\",\"username\":\"{{ user }}\",\"password\":\"{{ pass }}\"}"

- name: Activate Cluster
  uri:
    url: http://{{user}}:{{pass}}@{{masternode}}:5984/
    method: GET
    force_basic_auth: yes
  run_once: true

- name: Finish cluster
  uri:
    url: http://{{user}}:{{pass}}@{{masternode}}:5984/_cluster_setup
    method: POST
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    status_code: 200, 201
    body_format: json
    body: "{\"action\":\"finish_cluster\"}"    
  run_once: true
