# Part of Assignment 2 - COMP90024 Cluster and Cloud Computing 2022 S1
#
# Team 28
# 
# Authors: 
#
#  * Yuanzhi Shang (Student ID: 1300135)
#  * Zuguang Tong (Student ID: 1273868)
#  * Ruoyi Gan (Student ID: 987838)
#  * Zixuan Guo (Student ID: 1298930)
#  * Jingyu Tan (Student ID: 1184788)
#
# Location: Melbourne
#

# Delete project directory
- name: Delete content & directory
  file:
    state: absent
    path: "/home/ubuntu/Melbourne-s-urban-livability"
  become: yes

# Clone harvester branch repo
- name: Git clone from remote public repo
  git:
    repo: "https://github.com/ZgTong/Melbourne-s-urban-livability.git"
    dest: "/home/ubuntu/Melbourne-s-urban-livability"
  become: yes
